/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MostReadRouteImport } from './routes/most-read'
import { Route as RssRouteImport } from './routes/rss'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiPublicRssDotxmlRouteImport } from './routes/api/public/rss[.]xml'
import { Route as YearMonthDaySlugRouteImport } from './routes/$year.$month.$day.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MostReadRoute = MostReadRouteImport.update({
  id: '/most-read',
  path: '/most-read',
  getParentRoute: () => rootRouteImport,
} as any)
const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRssDotxmlRoute = ApiPublicRssDotxmlRouteImport.update({
  id: '/api/public/rss.xml',
  path: '/api/public/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const YearMonthDaySlugRoute = YearMonthDaySlugRouteImport.update({
  id: '/$year/$month/$day/$slug',
  path: '/$year/$month/$day/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/most-read': typeof MostReadRoute
  '/rss': typeof RssRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/$year/$month/$day/$slug': typeof YearMonthDaySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/most-read': typeof MostReadRoute
  '/rss': typeof RssRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/$year/$month/$day/$slug': typeof YearMonthDaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/most-read': typeof MostReadRoute
  '/rss': typeof RssRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/$year/$month/$day/$slug': typeof YearMonthDaySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/most-read'
    | '/rss'
    | '/search'
    | '/category/$slug'
    | '/api/public/rss.xml'
    | '/$year/$month/$day/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/most-read'
    | '/rss'
    | '/search'
    | '/category/$slug'
    | '/api/public/rss.xml'
    | '/$year/$month/$day/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/most-read'
    | '/rss'
    | '/search'
    | '/category/$slug'
    | '/api/public/rss.xml'
    | '/$year/$month/$day/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  MostReadRoute: typeof MostReadRoute
  RssRoute: typeof RssRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ApiPublicRssDotxmlRoute: typeof ApiPublicRssDotxmlRoute
  YearMonthDaySlugRoute: typeof YearMonthDaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/most-read': {
      id: '/most-read'
      path: '/most-read'
      fullPath: '/most-read'
      preLoaderRoute: typeof MostReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss.xml': {
      id: '/api/public/rss.xml'
      path: '/api/public/rss.xml'
      fullPath: '/api/public/rss.xml'
      preLoaderRoute: typeof ApiPublicRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$year/$month/$day/$slug': {
      id: '/$year/$month/$day/$slug'
      path: '/$year/$month/$day/$slug'
      fullPath: '/$year/$month/$day/$slug'
      preLoaderRoute: typeof YearMonthDaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  MostReadRoute: MostReadRoute,
  RssRoute: RssRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  ApiPublicRssDotxmlRoute: ApiPublicRssDotxmlRoute,
  YearMonthDaySlugRoute: YearMonthDaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
