
REVOKE ALL ON FUNCTION public.has_role(UUID, public.app_role) FROM anon, authenticated, PUBLIC;
REVOKE ALL ON FUNCTION public.is_staff(UUID) FROM anon, authenticated, PUBLIC;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM anon, authenticated, PUBLIC;
REVOKE ALL ON FUNCTION public.update_updated_at_column() FROM anon, authenticated, PUBLIC;

INSERT INTO public.posts (title, slug, excerpt, content, cover_image, category_id, author_id, status, published_at, views, is_featured, is_opinion)
VALUES
('افتتاح مشروع تطويري كبير يعيد الحياة إلى قلب المدينة','opening-major-development-project','مشروع يشمل إعادة تأهيل الشوارع الرئيسية وتوسيع المساحات الخضراء ضمن خطة تنموية شاملة.','<p>شهدت المدينة اليوم افتتاح واحد من أكبر المشاريع التطويرية في السنوات الأخيرة، حيث يشمل المشروع إعادة تأهيل الشوارع الرئيسية وتوسيع المساحات الخضراء.</p><p>وأكد المسؤولون أن المشروع يمثل نقلة نوعية في مستوى الخدمات المقدمة للسكان، وسيتم استكمال المراحل المتبقية خلال العام القادم.</p>','https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='top-news'),(SELECT id FROM public.authors WHERE slug='editorial'),'published', now() - interval '2 hours', 2480, true, false),
('تقرير خاص: كيف تغيرت ملامح الحياة اليومية في شمسان','special-report-daily-life-shamsan','جولة ميدانية ترصد التحولات الاجتماعية والاقتصادية في المدينة خلال العام الماضي.','<p>في جولة ميدانية استمرت أسبوعًا، رصد فريق شمسان نيوز تحولات واسعة في نمط الحياة اليومية.</p><p>ويقول السكان إن التغيير بدأ يظهر في تفاصيل صغيرة قبل أن يتحول إلى ملامح واضحة.</p>','https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='shamsan-today'),(SELECT id FROM public.authors WHERE slug='ahmed-alsharabi'),'published', now() - interval '5 hours', 1890, true, false),
('اجتماع موسع لمناقشة خطة الخدمات للعام المقبل','expanded-meeting-services-plan','الاجتماع ناقش أولويات الكهرباء والمياه والطرق ضمن موازنة العام الجديد.','<p>عُقد اجتماع موسع ضم ممثلي الجهات الخدمية لمناقشة خطة العام المقبل.</p><p>وتم الاتفاق على رفع أولوية مشاريع المياه والطرق.</p>','https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='shamsan-today'),(SELECT id FROM public.authors WHERE slug='editorial'),'published', now() - interval '9 hours', 940, true, false),
('حين يصبح الإعلام المحلي ضرورة لا رفاهية','local-media-necessity','قراءة في دور المنصات المحلية في تشكيل الوعي العام ومواجهة التضليل.','<p>لم يعد الإعلام المحلي مجرد ناقل للأخبار، بل صار شريكًا في صناعة الوعي.</p><p>وتتطلب هذه المسؤولية معايير مهنية صارمة.</p>','https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='opinion'),(SELECT id FROM public.authors WHERE slug='sara-almaqtari'),'published', now() - interval '1 day', 1320, true, true),
('الاقتصاد المحلي بين الفرص والتحديات','local-economy-opportunities','مقاربة تحليلية لواقع السوق المحلي وفرص النمو المتاحة.','<p>يعيش الاقتصاد المحلي مرحلة انتقالية دقيقة تتطلب سياسات مرنة.</p>','https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='opinion'),(SELECT id FROM public.authors WHERE slug='ahmed-alsharabi'),'published', now() - interval '2 days', 760, false, true),
('صورة وتعليق: وجوه من السوق القديم','photo-comment-old-market','لقطة توثق حركة البيع والشراء في أحد أقدم أسواق المدينة.','<p>في السوق القديم، لا شيء يشبه شيئًا آخر؛ الأصوات والألوان تحكي تاريخًا كاملًا.</p>','https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='photo-comment'),(SELECT id FROM public.authors WHERE slug='editorial'),'published', now() - interval '3 days', 1120, false, false),
('مختارات الأسبوع: خمس قصص تستحق القراءة','weekly-selections-five-stories','مجموعة مختارة من التقارير والقصص الإنسانية التي نشرت هذا الأسبوع.','<p>اخترنا لكم خمس قصص تسلط الضوء على تفاصيل إنسانية بعيدة عن ضجيج الأخبار.</p>','https://images.unsplash.com/photo-1495020689067-958852a7765e?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='selections'),(SELECT id FROM public.authors WHERE slug='editorial'),'published', now() - interval '4 days', 610, false, false),
('من ذاكرة المكان: حكاية القلعة التاريخية','history-of-the-citadel','رحلة في تاريخ القلعة التي شهدت قرونًا من الأحداث.','<p>تقف القلعة شاهدة على قرون من التحولات، وتحتفظ جدرانها بحكايات لم تُروَ بعد.</p>','https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='heritage'),(SELECT id FROM public.authors WHERE slug='sara-almaqtari'),'published', now() - interval '5 days', 1450, false, false),
('تحت المجهر: قراءة في مؤشرات التعليم','under-microscope-education-indicators','تحليل معطيات العام الدراسي ومقارنتها بالأعوام السابقة.','<p>تشير المعطيات إلى تحسن نسبي في معدلات الالتحاق مقابل تحديات في جودة المخرجات.</p>','https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='under-microscope'),(SELECT id FROM public.authors WHERE slug='ahmed-alsharabi'),'published', now() - interval '6 days', 880, false, false),
('إضاءات عسكرية: دورات تدريبية لرفع الجاهزية','military-training-courses','اختتام دورات تدريبية متخصصة ضمن خطة التطوير السنوية.','<p>اختتمت سلسلة من الدورات التدريبية المتخصصة التي استهدفت رفع مستوى الجاهزية والانضباط.</p>','https://images.unsplash.com/photo-1579912437766-7896df6d3cd3?w=1200&q=80',(SELECT id FROM public.categories WHERE slug='military'),(SELECT id FROM public.authors WHERE slug='editorial'),'published', now() - interval '7 days', 700, false, false);
